addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.9.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.11")
addSbtPlugin("com.indoorvivants" % "sbt-commandmatrix" % "0.0.5")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta41")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.0")
